[package]
name = "cornell"
version = "0.1.0"
authors = ["Bruno Marques <bruno@bmarques.net>"]

[dependencies]
bootloader_precompiled = "0.3.0"

[package.metadata.bootimage]
default-target = "x86_64-cornell.json"